[dg]
application="Purview" 

[dg.logging]
level = "DEBUG"
format1 = "[%(asctime)s] {%(filename)s:%(lineno)d} %(levelname)s - %(message)s"

[dg.similarity]
in_file = 'P20_Elaboration/2000_Standard/IECP2-DG-MTD-v2.0c.xlsm'
out_file = 'P20_Elaboration/2000_Standard/IECP2-DG-MTD-Similarity.xlsx'


[dg.matching]
in_file = 'DG_IEC_STD_V10_MtdMatch.csv'
REPO_NAME = 'Digital-Center-Purview-Dev'