@startuml home.views
!pragma useIntermediatePackages false

class home.views.SimulationPerformance.SimulationPerformance {
}
class home.views.DmDataIntegrityCheckReportViews.DmDataIntegrityCheckReportViews {
}
class home.views.IntNotificationViews.IntNotificationCountView {
}
class home.views.IntNotificationViews.IntNotificationCountViewByUsername {
}
class home.views.IntNotificationViews.IntNotificationListView {
}
class home.views.FCSTInformationViews.fcst_information_object {
  exact_part_group: None
  category_name: None
  ty_jan: None
  ty_feb: None
  ty_mar: None
  ty_apr: None
  ty_may: None
  ty_jun: None
  ty_jul: None
  ty_aug: None
  ty_sep: None
  ty_oct: None
  ty_nov: None
  ty_dec: None
  ty_month_to_year_end: None
  ny_jan: None
  ny_feb: None
  ny_mar: None
  ny_apr: None
  ny_may: None
  ny_jun: None
  ny_jul: None
  ny_aug: None
  ny_sep: None
  ny_oct: None
  ny_nov: None
  ny_dec: None
  ny_month_to_year_end: None
  gap_latest_bp: None
  gap_latest_baseline: None
  fcst_month_to_year_end: None
}
class home.views.FCSTPricesSettingViews.header_table_object {
  header_name: None
  os_view: None
  op_view: None
}
class home.views.TestfilterAndEdittable.vendor_survey_object {
  vendor_code: None
  vendor_name: None
  pn_amount: None
  expense_amount: None
  sum_amount: None
  year_record: None
  amount_acc: None
  acc_percentage: None
  buyer: None
  next_year_result: None
  this_year_result: None
  last_year_result: None
  second_last_year_result: None
}
class home.views.VendorFinancialRiskInvestigateList.vendor_survey_object {
  vendor_code: None
  vendor_name: None
  pn_amount: None
  expense_amount: None
  sum_amount: None
  year_record: None
  amount_acc: None
  acc_percentage: None
  buyer: None
  next_year_result: None
  this_year_result: None
  last_year_result: None
  second_last_year_result: None
}
class home.views.VendorHistoryPriceTrend.vendor_survey_object {
  vendor_code: None
  vendor_name: None
  pn_amount: None
  expense_amount: None
  sum_amount: None
  year_record: None
  amount_acc: None
  acc_percentage: None
  buyer: None
  next_year_result: None
  this_year_result: None
  last_year_result: None
  second_last_year_result: None
}
footer Generated by //py2puml//
@enduml

Successfully generated UML diagram for app "home.views".
